# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, home-manager, ... }:

{
  imports = [
    ../modules/music-production.nix
    home-manager.nixosModules.home-manager {
      home-manager.useGlobalPkgs = true;
      home-manager.useUserPackages = true;
      home-manager.users.lion = import ../users/lion.nix;
    }
  ];

  users.users.lion = {
    isNormalUser = true;
    description = "Lion";
    extraGroups = [ "networkmanager" "wheel" "pipewire"];
  };
}