# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, home-manager, ... }:

{
  imports = [
    home-manager.nixosModules.home-manager {
      home-manager.useGlobalPkgs = true;
      home-manager.useUserPackages = true;
      home-manager.users.raphael = import ../users/raphael.nix;
      home-manager.users.laura = import ../users/laura.nix;
    }
  ];

    networking = {
        hostName = lib.mkForce "powercouple";
    };

  users.users.raphael = {
    isNormalUser = true;
    description = "Raphaël";
    extraGroups = [ "networkmanager" "wheel"];
  };

  users.users.laura = {
    isNormalUser = true;
    description = "Laura";
    extraGroups = [ "networkmanager" "wheel"];
  };
}